import os
import termcolor as T
def log(s, col="green"):
    print (T.colored(s, col))
def main():
    log("copy test code from github")
    python3 = "sudo python3"
    log("run test code")
    os.mkdir("data")
    os.system(python3 + " test_spine_leaf_convergence.py -a 5")
    os.system(python3 + " test_spine_leaf_reconnected.py -a 5")
    os.system(python3 + " test_spine_leaf_convergence.py -a 10")
    os.system(python3 + " test_spine_leaf_reconnected.py -a 10")
    os.system(python3 + " test_spine_leaf_convergence.py -a 15")
    os.system(python3 + " test_spine_leaf_reconnected.py -a 15")
    os.system(python3 + " test_spine_leaf_tcp_arguement.py -b 1000")
    os.system(python3 + " test_spine_leaf_tcp_arguement.py -b 800")
    os.system(python3 + " test_spine_leaf_tcp_arguement.py -b 600")
    os.system(python3 + " test_spine_leaf_tcp_arguement.py -b 400")
    os.system(python3 + " test_spine_leaf_tcp_arguement.py -b 200")
    os.system(python3 + " test_spine_leaf_tcp_arguement.py -b 100")
    os.system(python3 + " test_spine_leaf_tcp_send_h1self.py")
    os.system(python3 + " test_spine_leaf_udp_send_h1self.py")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 1000 -B 1000")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 600 -B 1000")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 200 -B 1000")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 1000 -B 600")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 600 -B 600")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 200 -B 600")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 1000 -B 200")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 600 -B 200")
    os.system(python3 + " test_spine_leaf_udp_arguement.py -b 200 -B 200")
    os.system("mv ./data ../data")
if __name__ == "__main__":
    main()